language: csharp
solution: AivDraw.sln
notifications:
  email: false
install:
  - nuget restore AivDraw.sln
script:
  - msbuild /p:Configuration=Release /p:Platform=x64 AivDraw.sln
  - ls -l AivDraw/bin/x64/Release/*.dll
  - ls -l packages
  - ls -l packages/NUnit.ConsoleRunner.3.*/
  - ls -l packages/NUnit.ConsoleRunner.3.*/tools/
  - packages/NUnit.ConsoleRunner.3.*/tools/nunit3-console.exe Tests/bin/x64/Release/Tests.dll
deploy:
  - provider: script
    script: nuget pack ./AivDraw.nuspec -Verbosity detailed
            && nuget push ./Aiv.Draw.*.nupkg -Verbosity detailed -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
            && mkdir artifacts
            && mv *.nupkg artifacts
            && mv AivDraw/bin/x64/Release/*.dll artifacts
    on:
      repo: aiv01/aiv-draw
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: artifacts/*
    on:
      repo: aiv01/aiv-draw
      tags: true
    skip_cleanup: true