language: csharp
solution: AivDraw.sln
notifications:
  email: false
install:
  - nuget restore AivDraw.sln
  - sudo apt-get install doxygen
  
before_script:
  - export AUTO_YEAR=$(date +%Y)
  - export AUTO_TAG=$(if [ -z "$TRAVIS_TAG" ]; then echo "0.0.0"; else echo $TRAVIS_TAG; fi) 
script:
  - echo "=== BUILD ===\n" 
    && msbuild /p:Configuration=Release /p:Platform=x64 AivDraw.sln
    && ls -l AivDraw/bin/x64/Release/*.dll
  - echo "=== TEST ===\n"
    && packages/NUnit.ConsoleRunner.3.*/tools/nunit3-console.exe Tests/bin/x64/Release/Tests.dll
  - echo "=== PACKAGE ===\n" 
    && sed -i "s/@AUTO_TAG/$AUTO_TAG/" ./AivDraw.nuspec
    && sed -i "s/@AUTO_YEAR/$AUTO_YEAR/" ./AivDraw.nuspec
    && cat ./AivDraw.nuspec
    && nuget pack ./AivDraw.nuspec -Verbosity detailed
  - "=== DOCUMENTATION ===\n" 
    && doxygen
    && zip -r docs.zip auto-docs/html
  - "=== ARTIFACTS ===\n"
    && mkdir artifacts
    && mv *.nupkg artifacts/
    && mv AivDraw/bin/x64/Release/*.dll artifacts/
    && mv docs.zip artifacts/
    && ls -l artifacts/
 
deploy:
  - provider: script
    script: nuget pack ./AivDraw.nuspec -Verbosity detailed
            nuget push ./Aiv.Draw.*.nupkg -Verbosity detailed -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
            && mkdir artifacts
            && mv *.nupkg artifacts
            && mv AivDraw/bin/x64/Release/*.dll artifacts
    on:
      repo: aiv01/aiv-draw
      tags: true
    skip_cleanup: true
    
  - provider: pages
    github_token: $GITHUB_API_KEY
    local_dir: auto-docs/html
    on:
      branch: issue-6-Automate_ApiDoc_generation
      #tags: true
    skip_cleanup: true
    
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: artifacts/*
    on:
      repo: aiv01/aiv-draw
      tags: true
    skip_cleanup: true