language: java
#solution: AivDraw.sln
notifications:
  email: false
install:
  - echo "[FDF] Install"
script:
  - echo "[FDF] Build"
deploy:
  - provider: script
    script: echo "[FDF] Nuget pack" & touch pippo.txt & ls -la
    #- nuget push ./AivDraw.*.nupkg -Verbosity detailed -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
    on:
      repo: aiv01/aiv-draw
      tags: true
    #skip_cleanup: true
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: pippo.txt
    on:
      repo: aiv01/aiv-draw
      tags: true
    #skip_cleanup: true