language: csharp
solution: AivDraw.sln
install:
  - nuget restore AivDraw.sln
script:
  - msbuild /p:Configuration=Release AivDraw.sln
deploy:
  skip_cleanup: true
  provider: script
  script:
    - nuget pack ./AivDraw.nuspec -Verbosity detailed