name: CI Action

on:
  push:
      branches: 
        - '**'
        - '!master'
  pull_request:
      branches:
        - '**'
jobs:
  build:
      name: Build Job
      runs-on: windows-2019
      env:
        BUILD_DIR: ${{ github.workspace }}${{ matrix.SEP }}build
        AUTO_PATH_SLN: AivDraw.sln
        AUTO_PATH_LIBR_DLL: AivDraw\bin\Release\AivDraw.dll
        AUTO_PATH_TEST_DLL: Tests\bin\Release\Tests.dll
        AUTO_PATH_DOCS: auto-docs\html
        AUTO_PATH_ARTIFACTS: artifacts
      steps:
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1
          with:
            msbuild-architecture: x64
        - name: Checkout
          uses: actions/checkout@v2
        - name: List Workspace
          run: dir ${{ github.workspace }}
        - name: Compile
          run: |
            nuget restore ${{env.AUTO_PATH_SLN}}
            msbuild /p:Configuration=Release ${{env.AUTO_PATH_SLN}}
            dir ${{env.AUTO_PATH_LIBR_DLL}}
        - name: Test
          run: packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ${{env.AUTO_PATH_TEST_DLL}}
        - name: Prova
          run: |
            $year=Get-Date -Format "yyyy"
            echo "Current Year: $year"
        - name: Documentation
          run: |
            choco install doxygen.install
            $Env:PATH += ";C:\Program Files\doxygen\bin"
            doxygen
            Compress-Archive -Path $AUTO_PATH_DOCS -DestinationPath docs.zip
        - name: Artifacts
          run: |
            cp *.nuget  $AUTO_PATH_ARTIFACTS
            cp docs.zip $AUTO_PATH_ARTIFACTS
            
            
          
