name: CI Action

on:
  push:
      branches: 
        - '**'
        - '!master'
  pull_request:
      branches:
        - '**'
jobs:
  build:
      name: Build Job
      runs-on: windows-2019
      env:
        BUILD_DIR: ${{ github.workspace }}${{ matrix.SEP }}build
      steps:
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1
        - name: Checkout
          uses: actions/checkout@v2
        - name: List Workspace
          run: dir ${{ github.workspace }}
        - name: Compile
          run: |
            msbuild -version
            